"""trips, stops and trip activities

Revision ID: 01c372973625
Revises: b3dc7f0b825b
Create Date: 2026-08-22 13:32:44.701514

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01c372973625'
down_revision: str | None = 'b3dc7f0b825b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('cover_photo_url', sa.Text(), nullable=True),
    sa.Column('travelers', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='USD', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('share_slug', sa.String(length=16), nullable=True),
    sa.Column('copied_from_trip_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_trips_dates_ordered')),
    sa.CheckConstraint('travelers >= 1', name=op.f('ck_trips_travelers_positive')),
    sa.ForeignKeyConstraint(['copied_from_trip_id'], ['trips.id'], name=op.f('fk_trips_copied_from_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('share_slug', name=op.f('uq_trips_share_slug'))
    )
    op.create_index('ix_trips_share_slug_public', 'trips', ['share_slug'], unique=False, postgresql_where=sa.text('is_public'))
    op.create_index('ix_trips_user_id_start_date_desc', 'trips', ['user_id', sa.text('start_date DESC')], unique=False)
    op.create_table('trip_stops',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_trip_stops_dates_ordered')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_trip_stops_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_stops_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_stops')),
    sa.UniqueConstraint('trip_id', 'order_index', deferrable=True, initially='DEFERRED', name=op.f('uq_trip_stops_trip_id_order_index'))
    )
    op.create_index('ix_trip_stops_trip_id_order_index', 'trip_stops', ['trip_id', 'order_index'], unique=False)
    op.create_table('trip_activities',
    sa.Column('trip_stop_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', postgresql.ENUM(name='activity_category', create_type=False), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_trip_activities_cost_non_negative')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_trip_activities_duration_minutes_positive')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_trip_activities_activity_id_activities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], name=op.f('fk_trip_activities_trip_stop_id_trip_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_activities'))
    )
    op.create_index('ix_trip_activities_stop_date_order', 'trip_activities', ['trip_stop_id', 'scheduled_date', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_activities_stop_date_order', table_name='trip_activities')
    op.drop_table('trip_activities')
    op.drop_index('ix_trip_stops_trip_id_order_index', table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_index('ix_trips_user_id_start_date_desc', table_name='trips')
    op.drop_index('ix_trips_share_slug_public', table_name='trips', postgresql_where=sa.text('is_public'))
    op.drop_table('trips')
    # ### end Alembic commands ###
