"""catalog: city display metadata

Revision ID: b3dc7f0b825b
Revises: 638f8090ac82
Create Date: 2026-08-22 13:02:58.801573

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3dc7f0b825b'
down_revision: str | None = '638f8090ac82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('cities', sa.Column('best_season', sa.String(length=40), nullable=True))
    op.add_column('cities', sa.Column('avg_daily_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'avg_daily_cost')
    op.drop_column('cities', 'best_season')
    op.drop_column('cities', 'tags')
    # ### end Alembic commands ###
