"""budget items

Revision ID: c0173d4e0491
Revises: 01c372973625
Create Date: 2026-08-22 13:52:56.089255

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0173d4e0491'
down_revision: str | None = '01c372973625'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_items',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('trip_stop_id', sa.UUID(), nullable=True),
    sa.Column('category', postgresql.ENUM('TRANSPORT', 'ACCOMMODATION', 'MEALS', 'ACTIVITIES', 'MISC', name='budget_category'), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_budget_items_amount_non_negative')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_budget_items_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], name=op.f('fk_budget_items_trip_stop_id_trip_stops'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_items'))
    )
    op.create_index('ix_budget_items_trip_id_incurred_on', 'budget_items', ['trip_id', 'incurred_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_budget_items_trip_id_incurred_on', table_name='budget_items')
    op.drop_table('budget_items')
    # create_table creates the enum type; drop_table does not remove it.
    sa.Enum(name='budget_category').drop(op.get_bind())
